---
APPLY_FIXES: all

PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT

DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - REPOSITORY_GRYPE
  - JSON_JSONLINT
  - MAKEFILE_CHECKMAKE

