---
APPLY_FIXES: all

PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_BANDIT_CONFIG_FILE: .bandit.yml

DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - REPOSITORY_GRYPE
  - JSON_JSONLINT
  - MAKEFILE_CHECKMAKE
